""" Node functions definition for the RAG workflow."""
import os
from .state import GraphState
from ckb_back_end.modules.labs_nlp.llm_client_interface import LLMClientInterface
from ckb_back_end.utils.logging_config import get_configured_logger
from ckb_back_end.utils.utils import load_prompt_template

# Set up logging
logger = get_configured_logger(__name__)

consistency_check_prompt = load_prompt_template(os.path.join(os.path.dirname(__file__), 'consistency_check_prompt.txt'))


async def retrieve_node(state: GraphState, retriever, query_processor) -> GraphState:  # type: ignore[no-untyped-def] # Missing the type annotations because the retriever and the query_processor can be of different types
    """Retrieves documents and builds context based on the user's query.

    This node processes the initial query using the query processor, fetches
    relevant documents using the retriever, and then constructs a RAG context
    string from these documents.

    Args:
        state (GraphState): A dictionary representing the current graph's
            state, expected to contain the 'query' key field.
        retriever: The object responsible for retrieving documents and building
            the RAG context.
        query_processor: The object responsible for processing (e.g., rewriting)
            the initial query.

    Returns:
        GraphState: The updated graph's state, updating the 'query',
        'rewritten_query', 'documents', and 'context' key fields.
    """
    logger.debug("\nRetrieving node start.")
    query = state["query"]

    rewritten_query = await query_processor.process(query=query)

    documents = await retriever.retrieve(query=rewritten_query, )
    context = retriever.build_rag_context(documents)

    logger.debug("Retrieving node end.")
    return {"query": query, "rewritten_query": rewritten_query,
            "documents": documents, "prompt": consistency_check_prompt,
            "context": context}  # type: ignore[typeddict-item]


async def generate_node(state: GraphState, llm_client: LLMClientInterface) -> GraphState:
    """Generates a response using an LLM based on the context and query.

    This node takes the processed query and the constructed RAG context,
    and uses an LLM to generate the final output.

    Args:
        state (GraphState): A dictionary representing the current graph's
            state, expected to contain 'query' and 'context' keys.
        llm_client (LLMClientInterface): An instance of the LLMClientInterface
            used for making the LLM call.

    Returns:
        GraphState: An updated dictionary representing the graph's state,
            updating the 'output' key field, generated by the LLM.
    """
    logger.debug("\nGenerating node start.")
    query = state["query"]
    context = state["context"]
    consistency_check_prompt = state["prompt"]

    logger.debug("Debug, context for the LLM, based on the retrieved documents:\n", context)

    with open('context.txt', 'wt') as f:
        f.writelines(str(context))

    output = await llm_client.rag_llm_call(query=query, context=context, prompt=consistency_check_prompt)

    logger.debug("Generating node done.")
    return {"output": output}  # type: ignore[typeddict-item]
