version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    groups:
      github-workflows:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
