"""API for chat."""

from fastapi import HTTPException, Query, status, Depends
from fastapi.routing import APIRouter
from typing import Any, Optional

from aletheia_back_end.api.chat.dependencies import AuthUser
from aletheia_back_end.utils.logging_config import get_configured_logger
from aletheia_back_end.utils.utils import get_config_rag_workflow_app

from .models import ChatIn, ChatOut, ChatResponse

# Set up logging
logger = get_configured_logger(__name__)

chat_router: APIRouter = APIRouter(prefix="/v1")
__all__: list[str] = ["chat_router"]


@chat_router.post(
    "/chat",
    response_model=ChatOut,
    response_model_exclude_none=True,
    status_code=status.HTTP_200_OK,
    description="Post chat.",
)
async def post_chat(request: ChatIn,
                    auth_user: AuthUser,
                    rag_workflow_app: Any = Depends(get_config_rag_workflow_app),
                    party_id: Optional[str | int] = Query(None, description="Optional political party ID")
) -> ChatOut:
    """Endpoint for Aletheia chat. Handles incoming chat requests, retrieves
    relevant documents, and generates a response using an LLM.

    This asynchronous function first authenticates the user. Upon successful
    authentication, it processes a chat input, extracts the user's query and
    optional party_id. The RAG workflow is then run where a similarity search
    is perfomed on the vector store to retrieve relevant documents, a context
    is constructed from these documents, and an LLM generates a response.

    Args:
        request (ChatIn): A ChatIn object containing the user's messages and
            context overrides.
        auth_user (AuthUser): The authenticated username, ensuring the request
            is authorized before processing.
        rag_workflow_app (Any): Dependency to retrieve the configured RAG
            workflow application instance.
        party_id (Optional[str | int]): Optional political party ID to filter
            context retrieval.

    Returns:
        ChatOut: A ChatOut object containing the AI's response. This will
            include an error message if an unexpected exception occurs during
            processing.

    Raises:
        HTTPException: If the authentication fails (status code 401) or
            if the input query is empty (status code 400).
    """
    logger.info("Chat requested by authenticated user: %s", auth_user)

    try:
        query = request.messages[0].content

        logger.debug("Received input: %s ", request.model_dump())

        # Invoke the LangGraph RAG workflow
        logger.debug("\nStarting RAG workflow.")
        workflow_input = {"query": query, "party_id": None}

        if party_id:
            logger.debug("PartyID provided: %s", party_id)
            workflow_input["party_id"] = party_id

        logger.debug("Debug, workflow_input: ", workflow_input)
        response = await rag_workflow_app.ainvoke(workflow_input)

        # Extract the final output through GraphState's "output".
        final_answer = response.get(
            "output", "No answer was generated by the workflow."
        )
        logger.debug("\nDebug, final output based on the query and context:\n", final_answer)

        return ChatOut(delta=ChatResponse(content=final_answer, role="assistant"))
    except HTTPException as e:
        raise e
    except Exception as e:
        logger.error(f"Error processing chat: {str(e)}")
        return ChatOut(delta=ChatResponse(content=f"Error: {str(e)}", role="assistant"))
