"""State class definition for the LangGraph RAG workflow."""
from typing_extensions import TypedDict
from langchain_core.documents import Document


class GraphState(TypedDict):
    """
    Represents the state of the graph.

    Attributes:
        query: The user's query.
        party_id: The political party ID to filter documents. If None, no
            filtering is applied.
        documents: List of retrieved documents  # TODO: This can probably be
            taken out.
        context: Context given to the LLM in string format, based on the
            retrieved documents.
        output: The final output generated by the LLM.
    """
    query: str
    party_id: str | int | None
    rewritten_query: str
    documents: list[Document]
    context: str
    output: str
