""" Node functions definition for the RAG workflow."""
from .state import GraphState
from aletheia_back_end.modules.labs_nlp.llm_client_interface import LLMClientInterface
from aletheia_back_end.utils.logging_config import get_configured_logger

# Set up logging
logger = get_configured_logger(__name__)


async def expand_queries_node(state: GraphState, query_processor) -> GraphState:  # type: ignore[no-untyped-def] # Missing the type annotations because the query_processor can be of different types
    """Expands the original query into multiple detailed queries.

    This node takes the original user query and uses the query processor to
    generate multiple expanded queries that are more specific and detailed.
    These expanded queries can then be used to retrieve more relevant
    information.

    Args:
        state (GraphState): A dictionary representing the current graph's
            state, expected to contain the 'query' key field.
        query_processor: The object responsible for processing (e.g., rewriting)
            the initial query.

    Returns:
        GraphState: The updated graph's state, updating the 'query' and
        'expanded_queries' key fields.
    """
    logger.debug("\nExpanding queries node start.")
    query = state["query"]

    # This holds the raw formatted string from the LLM (e.g., "1. query A\n2. query B")
    raw_expanded_queries = await query_processor.process(query=query)
    # This holds the parsed list of expanded queries (e.g., ["query A", "query B"])
    expanded_queries = query_processor._parse_llm_response(raw_expanded_queries)

    logger.debug("Expanding queries node end.")
    return {"expanded_queries": expanded_queries}  # type: ignore[typeddict-item]


async def retrieve_node(state: GraphState, index: int, retriever) -> GraphState:  # type: ignore[no-untyped-def] # Missing the type annotations because the retriever and the query_processor can be of different types
    """Retrieves documents based on one of the expanded queries.

    Args:
        state (GraphState): A dictionary representing the current graph's
            state, expected to contain the 'query' key field.
        retriever: The object responsible for retrieving documents and building
            the RAG context.

    Returns:
        GraphState: The updated graph's state, updating the 'query',
        and 'documents' key fields.
    """
    logger.debug("\nRetrieving node start.")
    query = state["expanded_queries"][index]
    party_id = state["party_id"]

    documents = await retriever.retrieve(query=query, party_id=party_id)

    logger.debug("Retrieving node end.")
    return {"documents": documents}  # type: ignore[typeddict-item]


async def gather_and_rerank_node(state: GraphState, reranker) -> GraphState:  # type: ignore[no-untyped-def] # Missing the type annotations because the retriever can be of different types
    """Gathers and reranks documents from multiple retrieval branches.

    This node collects documents retrieved from multiple branches (each
    corresponding to an expanded query), combines them, and then reranks them
    based on their relevance to the original user query. The top-ranked
    documents are then used to build the final RAG context.

    Args:
        state (GraphState): A dictionary representing the current graph's
            state, expected to contain the 'expanded_queries' and multiple
            'documents_branch_{i}' key fields.
        reranker: The object responsible for reranking documents and building
            the RAG context.
        original_query (str): The original user query.

    Returns:
        GraphState: The updated graph's state, updating the 'context' key
        field with the constructed RAG context.
    """
    logger.debug("\nGathering and reranking node start.")

    all_documents = state["documents"]
    original_query = state["query"]

    reranked_documents = await reranker.rerank(query=original_query, documents=all_documents)
    context = reranker.build_rag_context(documents=reranked_documents)

    logger.debug("Gathering and reranking node end.")
    return {"context": context}  # type: ignore[typeddict-item]


async def generate_node(state: GraphState, llm_client: LLMClientInterface, prompt: str) -> GraphState:
    """Generates a response using an LLM based on the context and query.

    This node takes the processed query and the constructed RAG context,
    and uses an LLM to generate the final output.

    Args:
        state (GraphState): A dictionary representing the current graph's
            state, expected to contain 'query' and 'context' keys.
        llm_client (LLMClientInterface): An instance of the LLMClientInterface
            used for making the LLM call.

    Returns:
        GraphState: An updated dictionary representing the graph's state,
            updating the 'output' key field, generated by the LLM.
    """
    logger.debug("\nGenerating node start.")
    query = state["query"]
    context = state["context"]

    logger.debug("Debug, context for the LLM, based on the retrieved documents:\n", context)

    with open('context.txt', 'wt') as f:
        f.writelines(str(context))

    output = await llm_client.rag_llm_call(query=query, context=context, prompt=prompt)

    logger.debug("Generating node done.")
    return {"output": output}  # type: ignore[typeddict-item]
