"""State class definition for the LangGraph RAG workflow."""
import operator
from typing import Annotated
from typing_extensions import TypedDict
from langchain_core.documents import Document


class GraphState(TypedDict):
    """
    Represents the state of the graph.

    Attributes:
        query: The user's query.
        expanded_queries: List of expanded queries generated from the original
            query.
        party_id: The political party ID to filter documents. If None, no
            filtering is applied
        documents: List of retrieved documents  # TODO: This can probably be
            taken out.
        context: Context given to the LLM in string format, based on the
            retrieved documents.
        output: The final output generated by the LLM.
    """
    query: str
    expanded_queries: list[str]
    party_id: str | int | None
    documents: Annotated[list[Document], operator.add]
    context: str
    output: str
