"""State class definition for the LangGraph RAG workflow."""
import operator
from typing import Annotated
from typing_extensions import TypedDict
from langchain_core.documents import Document


class GraphState(TypedDict):
    """
    Represents the state of the graph.

    Attributes:
        query: The user's query.
        documents: List of retrieved documents  # TODO: This can probably be taken out.
        context: Context given to the LLM in string format, based on the retrieved documents.
        output: The final output generated by the LLM.
    """
    query: str
    expanded_queries: list[str]
    documents: Annotated[list[Document], operator.add]
    context: str
    output: str
