rag_workflow:
  llm:
    type: AzureOpenAIClient  # Or OpenAIClient
    params:
      prompt: |
            """ 
            # You are an expert fact-checker.
            # You fact-check the human input by the context you are provided.
            # You can only answer based on the context and you have to cite the source.
            # If you are unsure or if the context does not provide you with enough information, then answer with: "I do not know"
            # Do not yap. You should be concise, practical and precise.
            # Do not return anything else than the exact JSON format you are told to return.


            Answer in the following JSON format: 

            {{
              "possible": "bool: is it possible to answer this form the context provided?",
              "true": "bool: is the input from the user true or false based on the context?",
              "score": "On 0. to 1.: how true on FP16",
              "source": "The 'url' from context on which you based you answer",
              "content": "The content from the source on which you based your answer. Reduce this to max 256 characters"
            }}
            """
      temperature: 0.2
      max_tokens: 5000
      timeout: 40

  vector_store:
    type: AzureCosmosDBNoSqlVectorSearch # Currently it's the only option, so it's not used
    params:
      top_k: 5
      filter: None
      search_type: "similarity"
      embeddings:
        type: AzureOpenAIEmbeddings # Or OpenAIEmbeddings

  retriever:
    type: RerankingRetriever # Or BasicRetriever
    params:
      top_k_initial: 10
      top_n_reranked: 5
      rerank_prompt: |
            """On a scale of 1-10, rate the relevance of the following document to the query.
                Respond with only the numerical score.
                query: {query}
                Document: {doc}
                Relevance Score:
            """

  query_processor:
    type: QueryRewriter
    params:
      prompt: |
        """
        You are an AI assistant tasked with reformulating user queries to improve retrieval in a RAG system.
        Given the original query, rewrite it to be more specific, detailed, and likely to retrieve relevant information.

        Original query: {original_query}

        Rewritten query:
        """