"""API for chat."""

from fastapi import HTTPException, status, Depends
from fastapi.routing import APIRouter
from typing import Any

from aletheia_back_end.modules.workflows.rag.rag_graph import get_rag_workflow_app
from aletheia_back_end.utils.logging_config import get_configured_logger

from .models import ChatIn, ChatOut, ChatResponse

# Set up logging
logger = get_configured_logger(__name__)

lfc_router: APIRouter = APIRouter(prefix="/v1")
__all__: list[str] = ["lfc_router"]


@lfc_router.post(
    "/fact-check",
    response_model=ChatOut,
    response_model_exclude_none=True,
    status_code=status.HTTP_200_OK,
    description="Post speech.",
)
async def post_chat(request: ChatIn, rag_workflow_app: Any = Depends(get_rag_workflow_app)
) -> ChatOut:
    """Endpoint for Aletheia chat. Handles incoming chat requests, retrieves
    relevant documents, and generates a response using an LLM.

    This asynchronous function processes a chat input and extracts the user's
    query. The RAG workflow is then run where a similarity search is perfomed
    on the vector store to retrieve relevant documents, a context is
    constructed from these documents, and an LLM generates a response.

    Args:
        request (ChatIn): A ChatIn object containing the user's messages and
            context overrides.

    Returns:
        ChatOut: A ChatOut object containing the AI's response. This will
            include an error message if an unexpected exception occurs during
            processing.

    Raises:
        HTTPException: If the input query is empty (status code 400).
    """
    try:
        # Extract query and parameters
        if not request.messages or not request.messages[0].content:
            raise HTTPException(400, "Query cannot be empty")
        query = request.messages[0].content
        party_id = request.party
        # top_k = request.context.overrides.top  # TODO: Implement top_k in context overrides
        # temperature = request.context.overrides.temperature  # TODO: Implement temperature in context overrides

        logger.debug("Received input: %s ", request.model_dump())

        # Invoke the LangGraph RAG workflow
        logger.debug("\nStarting RAG workflow.")
        response = await rag_workflow_app.ainvoke({"query": query,
                                                   "party_id": party_id})

        # Extract the final output through GraphState's "output".
        final_answer = response.get(
            "output", "No answer was generated by the workflow."
        )
        logger.debug("\nDebug, final output based on the query and context:\n", final_answer)

        return ChatOut(delta=ChatResponse(content=final_answer, role="assistant"))
    except HTTPException as e:
        raise e
    except Exception as e:
        logger.error(f"Error processing chat: {str(e)}")
        return ChatOut(delta=ChatResponse(content=f"Error: {str(e)}", role="assistant"))
