name: Deploy Python project to Production in Azure Web App

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'aletheia-back-end-test'  # App Service name
  WORKING_DIRECTORY: 'src'             # Deploy the src folder
  PYTHON_VERSION: '3.13'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE_PRODUCTION }}
          package: ${{ env.WORKING_DIRECTORY }}
